; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:sparkfun_samd21_proRF]
platform = atmelsam
board = sparkfun_samd21_proRF
framework = arduino
lib_ldf_mode = chain+
monitor_speed = 9600
lib_archive = no
lib_deps = 
    SPI
    arduino-libraries/SD@^1.3.0
build_flags = 
    -Wno-comment
    -Iinclude
    -Ilib/RadioHead
    ; Force the compiler to see the framework SPI folder
    -isystem $PLATFORMIO_CORE_DIR/packages/framework-arduino-samd/libraries/SPI/src
check_tool = cppcheck
check_skip_packages = yes
check_flags =
  cppcheck: -I include -I lib/RadioHead --suppress=unusedFunction --inline-suppr

;extra_scripts = post:rename_firmware.py


[env:sender]
extends = env:sparkfun_samd21_proRF
; Include main.cpp and the Send file, ignore Receive
build_src_filter = +<main.cpp> +<fileTransferSend.cpp> -<fileTransferReceive.cpp>

[env:receiver]
extends = env:sparkfun_samd21_proRF
; Include main.cpp and the Receive file, ignore Send
build_src_filter = +<main.cpp> +<fileTransferReceive.cpp> -<fileTransferSend.cpp>